import { CountContextProvider } from './context/count'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CountContextProvider>
        {children}

        </CountContextProvider>
        </body>
    </html>
  )
}
