import "./globals.css";
import Header from "./components/Header";
import { UserContextProvider } from "./context/user";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <Header />
          <main>{children}</main>
        </UserContextProvider>
      </body>
    </html>
  );
}
